name: Database Backup
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger backup creation
        run: |
          echo "Triggering backup..."
          curl -f "https://mein-computerfreund.de/create_backup.php?token=${{ secrets.BACKUP_TOKEN }}" || { echo "Backup trigger failed"; exit 1; }

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Check FTPS backups
        env:
          SSHPASS: ${{ secrets.FTP_PASSWORD }}
        run: |
          echo "Checking backups..."
          sshpass -e sftp -o StrictHostKeyChecking=no -P 2222 ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }} << EOF
          cd /htdocs/html/skyrun/backups
          ls -l
          bye
          EOF