name: SFTP Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install sshpass
        run: sudo apt-get install -y sshpass
      
      - name: Create exclude file
        run: |
          echo ".git/" > exclude.txt
          echo ".github/" >> exclude.txt
          echo "*.sql" >> exclude.txt
          echo "*.code-workspace" >> exclude.txt
          echo "config.php" >> exclude.txt
          echo "*.log" >> exclude.txt
          echo "php_errors.log" >> exclude.txt
      
      - name: Prepare files for upload
        run: |
          mkdir -p temp_deploy
          rsync -av --exclude-from=exclude.txt . temp_deploy/
      
      - name: SFTP Upload
        env:
          SSHPASS: ${{ secrets.FTP_PASSWORD }}
        run: |
          sshpass -e sftp -o StrictHostKeyChecking=no -P 2222 ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }} << EOF
          cd /htdocs/html/skyrun/
          lcd temp_deploy
          put -r .
          bye
          EOF